Update simple_req_workflow.yml

diff --git a/req_workflows/simple_req_workflow.yml b/req_workflows/simple_req_workflow.yml
--- a/req_workflows/simple_req_workflow.yml
+++ b/req_workflows/simple_req_workflow.yml
@@ -7,16 +7,16 @@ jobs:
     steps:
       - name: Always pass
         run: exit 0
-  job-always-fail:
-    name: Failing job
-    runs-on: ubuntu-latest
-    steps:
-      - name: Always pass
-        run: exit 1
-#   job-to-be-skipped:
-#     if: false
-#     name: Skipped job
+#   job-always-fail:
+#     name: Failing job
 #     runs-on: ubuntu-latest
 #     steps:
-#       - name: Check out repository
-#         run: echo "Hello world"
+#       - name: Always pass
+#         run: exit 1
+  job-to-be-skipped:
+    if: false
+    name: Skipped job
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        run: echo "Hello world"
