Update simple_req_workflow.yml

diff --git a/req_workflows/simple_req_workflow.yml b/req_workflows/simple_req_workflow.yml
--- a/req_workflows/simple_req_workflow.yml
+++ b/req_workflows/simple_req_workflow.yml
@@ -1,18 +1,18 @@
 name: Test required workflow
 on: pull_request
 jobs:
-#   job-always-pass:
-#     name: Succesful job
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Always pass
-#         run: exit 0
-  job-always-fail:
-    name: Failing job
+  job-always-pass:
+    name: Succesful job
     runs-on: ubuntu-latest
     steps:
       - name: Always pass
-        run: exit 1
+        run: exit 0
+#   job-always-fail:
+#     name: Failing job
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Always pass
+#         run: exit 1
   job-to-be-skipped:
     if: false
     name: Skipped job
